### ISSUE TITLE
Rename "services offered", adjust sizes in Phone, Email, Seller

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#17]
Rename "services offered" panel in Phone, Email, Seller. Call it "Summary of products offered"

Make the "Images" panel taller so that one doesn't have to scroll so much to see the images.

Make the "offers per city" panel taller so that I don't have to scroll in a small box

The attached example shows that there is a lot of white space at the bottom and I have to scroll inside the little box to look at the images.

(image redacted)

**Comment by ThomasSchellenbergNextCentury** [comment]
In the future it would be helpful if you used a more encompassing title, since the title for this issue only references one of your 3 points.

Would you like the "Services Offered" section on the seller entity page to be renamed as well?

**Comment by szeke** [comment]
Yes, in all panels.
