### ISSUE TITLE
Email and phone pages are doing the wrong query to get locations

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#19]
The email and phone pages are doing the same query as the seller to get the location for the map and the "offers by city". This means that these pages are showing all the locations for the seller rather than just the locations for the email or phone.

```
http://localhost:5009/email.html?value=http://dig.isi.edu/ht/data/email/(email_redacted)&field=_id&blur=true
```

and

```
http://localhost:5009/phone.html?value=http://dig.isi.edu/ht/data/phone/(phone_redacted)&field=_id&blur=true
```

The correct query is:

```
GET offer/_search
{
  "aggs": {
    "localities_for_email": {
      "filter": {
        "term": {
          "mainEntityOfPage.mentions": "http://dig.isi.edu/ht/data/phone/(phone_redacted)"
        }
      },
      "aggs": {
        "localities": {
          "terms": {
            "field": "availableAtOrFrom.address.key"
          }
        }
      }
    }
  },
  "size": 0
}
```

The above query returns the correct locations for email and phone, the union of both is what shows on seller.

**Comment by szeke** [comment]
@saggu, @dkapoor this is really important to fix as the data we are showing is very wrong.

**Comment by dkapoor** [comment]
Have fixed this in development-isi branch

**Comment by szeke** [comment]
It works.
