### ISSUE TITLE
Images for seller are incorrect.

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#21]
For example, the following seller shows 25 images:

```
http://localhost:5009/seller.html?value=http://dig.isi.edu/ht/data/seller/cluster/18ABD818254679E158A7E257054900F7E02B6063&field=_id&blur=true
```

Note: after we reload the index, the seller may have a different URI. Phone number is 4157382305

There should be 46 images, not just 25. Makes sense to avoid showing all the images, as there could be many, but the display needs to state how many there are and how many are shown.

The following query uses aggregation to get distinct URLs. It is also possible to do a filter queyr on "image" as we KG is such that ImageObject and URL are one to one.

```
GET image/_search
{
  "aggs": {
    "images_for_email": {
      "filter": {
        "term": {
          "isImagePartOf.mainEntity.seller.uri": "http://dig.isi.edu/ht/data/seller/cluster/18ABD818254679E158A7E257054900F7E02B6063"
        }
      },
      "aggs": {
        "distinct_images": {
          "terms": {
            "field": "url.raw",
            "size": 25
          }
        }
      }
    }
  },
  "size": 0
}
```

The equivalent filter query is 

```
GET image/_search
{
  "query": {
    "filtered": {
      "query": {"match_all": {}},
      "filter": {
        "term": {
          "isImagePartOf.mainEntity.seller.uri": "http://dig.isi.edu/ht/data/seller/cluster/18ABD818254679E158A7E257054900F7E02B6063"
        }
      }
    }
  },
  "size": 25,
  "_source": {
    "include": "url"
  }
}
```

**Comment by ThomasSchellenbergNextCentury** [comment]
I have added a "show more" button to the photos section and have changed the title to show the correct total number of images.

The seller entity page already queries for images using `isImagePartOf.mainEntity.seller.uri` and the seller URI.  Please take a look and let me know if something else needs to be changed.

**Comment by szeke** [comment]
Is the last change in master?

**Comment by szeke** [comment]
Looks good.
