### ISSUE TITLE
Facets get confused and show ZERO when they shouldn't

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#22]
To reproduce:
1. Search for `(redacted)`
2. Facet phone `(redacted)`
3. Facet `New York` 

Now the count for the phone goes to ZERO. The number of offers shown is 4, which is correct, but the facet of the phone numbers shows many more counts than 4

**Comment by szeke** [comment]
@flyntde looks like this one is for you.

**Comment by ThomasSchellenbergNextCentury** [comment]
Moved to https://nextcentury.atlassian.net/browse/DIG-824
