### ISSUE TITLE
Show states in the "offers by city" summary

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#24]
So ambiguous names can be distinguished, and is compatible with the facets.

Tooltips on the map don't need the state.

**Comment by ThomasSchellenbergNextCentury** [comment]
Isn't this already the case?  You're talking about the "offers per city" aggregations below the map, right?

**Comment by szeke** [comment]
Yes, it is, my bad.

**Comment by szeke** [comment]
In seller the state is missing
