### ISSUE TITLE
Missing unicodes in ad

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#27]
The following offer should have lots of unicodes, but doesn't. The DIG 1 version shows the unicodes.

```
http://localhost:5009/offer.html?value=http://dig.isi.edu/ht/data/offer/46869AF48B5FCC8C579B0F9CA180C94ADB31663D6485BCA92C72902ED0588ED7&field=_id&blur=true
```

Someone please check whether the unicodes are in ES to figure out where they went missing.

**Comment by ThomasSchellenbergNextCentury** [comment]
Just looked at the offer in dig-1 and it seems like it's a data issue.
