### ISSUE TITLE
Offer not showing for web page

### ISSUE THREAD

**Issue by szeke** [NextCenturyCorporation/digapp-ht#4]
`http://localhost:5009/webpage.html?value=http://dig.isi.edu/ht/data/webpage/00747DB7D58909A347CECC61E8F13FC550089ACD22DB87369FC0E699A0C60F9E&field=_id`

The offers section is empty. The query does return an offer for this page

```
curl -X POST -H "Authorization: Basic <private password>" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "Postman-Token: d32c1d05-eab2-1265-1596-590dfb0cda73" -d '{
    "query": {
        "ids" : {
            "values" : [
                "http://dig.isi.edu/ht/data/webpage/00747DB7D58909A347CECC61E8F13FC550089ACD22DB87369FC0E699A0C60F9E"
            ]
        }
    }
}
' "http://52.39.180.16:8080/dig-latest/webpage/_search"
```

**Comment by szeke** [comment]
@dkapoor here is one place to start investigating the queries in the app. Looping @saggu too

**Comment by dkapoor** [comment]
Have moved this to the ISI fork. Mike, you can delete it from here. Thanks.

**Comment by ghost** [comment]
closing because this has migrated to usc-isi-i2/digapp-ht fork
